### ISSUE TITLE
Unable to find target command: docker_java_build on ST2

### ISSUE THREAD

**Issue by sfragata** [domeide/sublime-docker#21]
Hi, I've installed the package but when I'll run it the error rises

_Unable to find target command: docker_java_build_

Sublime Text 2 Version 2.0.2, build 2221

**Comment by sfragata** [comment]
More details

Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/Docker Based Build Systems/DockerBuild.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./DockerBuild.py", line 1, in <module>
    from . import dockerutils
ValueError: Attempted relative import in non-package
Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/Docker Based Build Systems/DockerClojureBuild.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./DockerClojureBuild.py", line 1, in <module>
    from . import dockerutils
ValueError: Attempted relative import in non-package
Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/Docker Based Build Systems/DockerJavaBuild.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./DockerJavaBuild.py", line 1, in <module>
    from . import dockerutils
ValueError: Attempted relative import in non-package
Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/Docker Based Build Systems/dockerutils.py
Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/HTML/encode_html_entities.py
Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/HTML/html_completions.py
Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/JSONLint/JSONLint.py
Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/JsFormat/js_formatter.py
Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/Package Control/Package Control.py
Reloading plugin <USER-PATH>/.config/sublime-text-2/Packages/Package Control/bootstrap.py
plugin init time: 0.115514
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.215115
using gamma: 1 (err: 0)
startup cache, total files: 106 cache hits: 106
startup time: 0.333717 (package setup was not run)
reloading <USER-PATH>/.config/sublime-text-2/Packages/User/ColorHighlighter.sublime-settings
loaded 837 snippets
Package Control: No updated packages
Unable to find target command: docker_java_build

**Comment by k1xme** [comment]
Which platform are you running ST2? On Mac OS or Linux? 'Cuz I thought it's gonna be related to the file path.

**Comment by sfragata** [comment]
Linux
